databases:
  - name: quizle
    databaseName: quiz_webapp_production_4koe
    user: quizle

services:
  - type: web
    name: plataformaquizle
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: quiz_webapp_production
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false